spring:
  datasource:
    platform: 'postgresql'
    url: 'jdbc:postgresql://127.0.0.1:5433/jwt_security_api'
    username: 'postgres'
    password: '123456'
  jpa:
    database-platform=org:
      hibernate:
        dialect: 'PostgreSQL10Dialect'
  jackson:
    time-zone: 'America/Bogota'
    locale: 'es_CO'
  devtools:
    add-properties: false

logging:
  level:
    web: debug
